let Database = {
    users: [
        {
            id: 1,
            name: "Jimmy Smith",
            email: "jimmy123@gmail.com",
            password: "jimmy123!",
            profile: "https://images.unsplash.com/photo-1599242460737-5174dba06145?ixid=MXwxMjA3fDB8MHx0b3BpYy1mZWVkfDIwN3xCbi1EanJjQnJ3b3x8ZW58MHx8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
            friends: [ {id: 3, name: "Jonathan Chen"} ],
        },
        {
            id: 2,
            name: "Johnny Doe",
            email: "johnny123@gmail.com",
            password: "johnny123!",
            profile: "https://images.unsplash.com/photo-1437448317784-3a480be9571e?ixid=MXwxMjA3fDB8MHx0b3BpYy1mZWVkfDc0fDZzTVZqVExTa2VRfHxlbnwwfHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
            friends: [],
        },
        {
            id: 3,
            name: "Jonathan Chen",
            email: "jonathan123@gmail.com",
            password: "jonathan123!",
            profile: "https://images.unsplash.com/photo-1520518372269-15c0819cdc08?ixid=MXwxMjA3fDB8MHx0b3BpYy1mZWVkfDMzfHRvd0paRnNrcEdnfHxlbnwwfHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
            friends: [ {id: 1, name: "Jimmy Smith"},{id: 2, name: "Johnny Doe"} ],
        },
    ],
    reminders: [
        {
            id: 1,
            user: 2,
            title: "Work",
            description: "abcabc",
            date: "2021-03-28T23:59",
            subtasks: [ "Subtask one", "Subtask two", "Subtask three", ],
            tags: [ "tag1", "tag2", "tag3", "tag4", "tag5", ],
            completed: true,
        },
        {
            id: 2,
            user: 3,
            title: "abc",
            description: "abcabc",
            date: "2021-03-28T23:59",
            subtasks: [ "Subtask one", "Subtask two", "Subtask three", ],
            tags: [ "tag1", "tag2", "tag3", "tag4", "tag5", ],
            completed: true,
        },
        {
            id: 3,
            user: 1,
            title: "Gym Membership",
            description: "Gym mebership renewal deadline.",
            date: "2021-03-30T16:00",
            subtasks: ["Check schedule for opening", ],
            tags: [ "workout", "gym", "due", "membership", ],
            completed: false,
        },
        {
            id: 4,
            user: 2,
            title: "abc",
            description: "abcabc",
            date: "2021-03-28T23:59",
            subtasks: [ "Subtask one", "Subtask two", "Subtask three", ],
            tags: [ "tag1", "tag2", "tag3", "tag4", "tag5", ],
            completed: true,
        },
        {
            id: 5,
            user: 1,
            title: "Checkup",
            description: "Biannual checkup appointment with Dr.",
            date: "2021-04-12T09:00",
            subtasks: [ "Subtask one", "Subtask two", "Subtask three", ],
            tags: [ "doctor", "checkup", "ihateneedles", ],
            completed: false,
        },
        {
            id: 6,
            user: 1,
            title: "abc",
            description: "abcabc",
            date: "2021-03-28T23:59",
            subtasks: [ "Subtask one", "Subtask two", "Subtask three", ],
            tags: [ "tag1", "tag2", "tag3", "tag4", "tag5", ],
            completed: true,
        },
        {
            id: 7,
            user: 3,
            title: "abc",
            description: "abcabc",
            date: "2021-03-28T23:59",
            subtasks: [ "Subtask one", "Subtask two", "Subtask three", ],
            tags: [ "tag1", "tag2", "tag3", "tag4", "tag5", ],
            completed: true,
        },
        {
            id: 8,
            user: 2,
            title: "abc",
            description: "abcabc",
            date: "2021-03-28T23:59",
            subtasks: [ "Subtask one", "Subtask two", "Subtask three", ],
            tags: [ "tag1", "tag2", "tag3", "tag4", "tag5", ],
            completed: true,
        },
        {
            id: 9,
            user: 2,
            title: "abc",
            description: "abcabc",
            date: "2021-03-28T23:59",
            subtasks: [ "Subtask one", "Subtask two", "Subtask three", ],
            tags: [ "tag1", "tag2", "tag3", "tag4", "tag5", ],
            completed: false,
        },
    ]
};

module.exports = Database;